/**
 * DOCX Document Utilities
 * ───────────────────────
 * Reusable building blocks for creating styled Word documents
 * using the `docx` npm package. No external template files.
 *
 * Phase 6A.5.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  HeadingLevel,
  ShadingType,
  convertMillimetersToTwip,
} from "docx";

// ═══════════════════════════════════════════════════════
// STYLE CONSTANTS
// ═══════════════════════════════════════════════════════

const FONT_NAME = "Calibri";
const FONT_SIZE_NORMAL = 22;   // half-points → 11pt
const FONT_SIZE_SMALL = 20;    // 10pt
const FONT_SIZE_HEADING = 26;  // 13pt
const FONT_SIZE_TITLE = 32;    // 16pt
const FONT_SIZE_SUBTITLE = 28; // 14pt

const COLOR_BRAND = "2D5F2D";  // GreenPeat dark green
const COLOR_DARK = "1A1A1A";
const COLOR_GRAY = "666666";
const COLOR_HEADER_BG = "2D5F2D";
const COLOR_HEADER_TEXT = "FFFFFF";

const CELL_MARGIN = {
  top: convertMillimetersToTwip(1),
  bottom: convertMillimetersToTwip(1),
  left: convertMillimetersToTwip(2),
  right: convertMillimetersToTwip(2),
};

const TABLE_BORDER = {
  style: BorderStyle.SINGLE,
  size: 1,
  color: "CCCCCC",
};

const TABLE_BORDERS = {
  top: TABLE_BORDER,
  bottom: TABLE_BORDER,
  left: TABLE_BORDER,
  right: TABLE_BORDER,
  insideHorizontal: TABLE_BORDER,
  insideVertical: TABLE_BORDER,
};

// ═══════════════════════════════════════════════════════
// DOCUMENT CREATION
// ═══════════════════════════════════════════════════════

/**
 * Create a new DOCX Document with default styling and metadata.
 *
 * @param sections  Array of section children (paragraphs, tables, etc.)
 */
export function createDocxDocument(
  sections: (Paragraph | Table)[]
): Document {
  return new Document({
    creator: "AgriCoX / GreenPeat",
    title: "Document",
    description: "Generated by AgriCoX Document System",
    styles: {
      default: {
        document: {
          run: {
            font: FONT_NAME,
            size: FONT_SIZE_NORMAL,
            color: COLOR_DARK,
          },
          paragraph: {
            spacing: { after: 120 },
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertMillimetersToTwip(20),
              bottom: convertMillimetersToTwip(20),
              left: convertMillimetersToTwip(25),
              right: convertMillimetersToTwip(20),
            },
          },
        },
        children: sections,
      },
    ],
  });
}

// ═══════════════════════════════════════════════════════
// TEXT ELEMENTS
// ═══════════════════════════════════════════════════════

/**
 * Create a document title paragraph (large, bold, green, centered).
 */
export function createTitle(text: string): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 80 },
    children: [
      new TextRun({
        text,
        bold: true,
        size: FONT_SIZE_TITLE,
        font: FONT_NAME,
        color: COLOR_BRAND,
      }),
    ],
  });
}

/**
 * Create a subtitle paragraph (medium, bold, centered).
 */
export function createSubtitle(text: string): Paragraph {
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 200 },
    children: [
      new TextRun({
        text,
        bold: true,
        size: FONT_SIZE_SUBTITLE,
        font: FONT_NAME,
        color: COLOR_GRAY,
      }),
    ],
  });
}

/**
 * Create a section heading (bold, green, left-aligned).
 */
export function createHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 300, after: 120 },
    children: [
      new TextRun({
        text,
        bold: true,
        size: FONT_SIZE_HEADING,
        font: FONT_NAME,
        color: COLOR_BRAND,
      }),
    ],
  });
}

/**
 * Create a regular paragraph.
 */
export function createParagraph(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        size: FONT_SIZE_NORMAL,
        font: FONT_NAME,
      }),
    ],
  });
}

/**
 * Create a metadata line: bold label + normal value.
 */
export function createMetadataParagraph(
  label: string,
  value: string
): Paragraph {
  return new Paragraph({
    spacing: { after: 60 },
    children: [
      new TextRun({
        text: label + " ",
        bold: true,
        size: FONT_SIZE_NORMAL,
        font: FONT_NAME,
      }),
      new TextRun({
        text: value,
        size: FONT_SIZE_NORMAL,
        font: FONT_NAME,
      }),
    ],
  });
}

/**
 * Create a spacer paragraph.
 */
export function createSpacer(): Paragraph {
  return new Paragraph({ spacing: { after: 200 }, children: [] });
}

// ═══════════════════════════════════════════════════════
// TABLE CREATION
// ═══════════════════════════════════════════════════════

/**
 * Create a styled table with header row and data rows.
 *
 * @param headers   Array of header column labels.
 * @param rows      Array of data rows (each row is an array of cell values).
 * @param colWidths Optional column widths in percentage (must sum to ~100).
 */
export function createTable(
  headers: string[],
  rows: string[][],
  colWidths?: number[]
): Table {
  // Header row
  const headerRow = new TableRow({
    tableHeader: true,
    children: headers.map((h, i) =>
      new TableCell({
        width: colWidths
          ? { size: colWidths[i], type: WidthType.PERCENTAGE }
          : undefined,
        shading: {
          type: ShadingType.SOLID,
          color: COLOR_HEADER_BG,
          fill: COLOR_HEADER_BG,
        },
        margins: CELL_MARGIN,
        children: [
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: h,
                bold: true,
                size: FONT_SIZE_SMALL,
                font: FONT_NAME,
                color: COLOR_HEADER_TEXT,
              }),
            ],
          }),
        ],
      })
    ),
  });

  // Data rows
  const dataRows = rows.map(
    (row) =>
      new TableRow({
        children: row.map(
          (cell, i) =>
            new TableCell({
              width: colWidths
                ? { size: colWidths[i], type: WidthType.PERCENTAGE }
                : undefined,
              margins: CELL_MARGIN,
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: cell,
                      size: FONT_SIZE_SMALL,
                      font: FONT_NAME,
                    }),
                  ],
                }),
              ],
            })
        ),
      })
  );

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: TABLE_BORDERS,
    rows: [headerRow, ...dataRows],
  });
}

/**
 * Create a simple two-column row (no header) for totals display.
 */
export function createTotalsTable(
  rows: Array<{ label: string; value: string; bold?: boolean }>
): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      insideHorizontal: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      insideVertical: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    },
    rows: rows.map(
      (r) =>
        new TableRow({
          children: [
            // Spacer (60%)
            new TableCell({
              width: { size: 60, type: WidthType.PERCENTAGE },
              children: [new Paragraph({ children: [] })],
            }),
            // Label (20%)
            new TableCell({
              width: { size: 20, type: WidthType.PERCENTAGE },
              margins: CELL_MARGIN,
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [
                    new TextRun({
                      text: r.label,
                      bold: true,
                      size: r.bold ? FONT_SIZE_NORMAL : FONT_SIZE_SMALL,
                      font: FONT_NAME,
                      color: r.bold ? COLOR_BRAND : COLOR_DARK,
                    }),
                  ],
                }),
              ],
            }),
            // Value (20%)
            new TableCell({
              width: { size: 20, type: WidthType.PERCENTAGE },
              margins: CELL_MARGIN,
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [
                    new TextRun({
                      text: r.value,
                      bold: r.bold,
                      size: r.bold ? FONT_SIZE_NORMAL : FONT_SIZE_SMALL,
                      font: FONT_NAME,
                      color: r.bold ? COLOR_BRAND : COLOR_DARK,
                    }),
                  ],
                }),
              ],
            }),
          ],
        })
    ),
  });
}

// ═══════════════════════════════════════════════════════
// SIGNATURE BLOCK
// ═══════════════════════════════════════════════════════

/**
 * Create a two-column signature block.
 */
export function createSignatureBlock(
  leftTitle: string,
  rightTitle: string
): Table {
  const signColumn = (title: string) =>
    new TableCell({
      width: { size: 50, type: WidthType.PERCENTAGE },
      margins: {
        top: convertMillimetersToTwip(3),
        bottom: convertMillimetersToTwip(3),
        left: convertMillimetersToTwip(5),
        right: convertMillimetersToTwip(5),
      },
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 40 },
          children: [
            new TextRun({
              text: title,
              bold: true,
              size: FONT_SIZE_NORMAL,
              font: FONT_NAME,
            }),
          ],
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 40 },
          children: [
            new TextRun({
              text: "(Ký, ghi rõ họ tên)",
              size: FONT_SIZE_SMALL,
              font: FONT_NAME,
              color: COLOR_GRAY,
              italics: true,
            }),
          ],
        }),
        // Blank space for signature
        new Paragraph({ spacing: { after: 600 }, children: [] }),
        new Paragraph({ spacing: { after: 600 }, children: [] }),
      ],
    });

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      bottom: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      left: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      right: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      insideHorizontal: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
      insideVertical: { style: BorderStyle.NONE, size: 0, color: "FFFFFF" },
    },
    rows: [
      new TableRow({
        children: [signColumn(leftTitle), signColumn(rightTitle)],
      }),
    ],
  });
}

// ═══════════════════════════════════════════════════════
// TEXT HELPERS
// ═══════════════════════════════════════════════════════

/**
 * Ensure a value is a safe non-empty string for DOCX rendering.
 */
export function safeDocxText(
  value: string | null | undefined,
  fallback: string = "—"
): string {
  if (value == null) return fallback;
  const trimmed = value.trim();
  return trimmed || fallback;
}

// ═══════════════════════════════════════════════════════
// EXPORT
// ═══════════════════════════════════════════════════════

/**
 * Convert a Document to a Buffer.
 */
export async function docxToBuffer(doc: Document): Promise<Buffer> {
  return Packer.toBuffer(doc) as Promise<Buffer>;
}
